["protostar.config"]
protostar_version = "0.2.0"

["protostar.project"]
libs_path = "./lib"

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]

# This section is explained in the "Project compilation" guide.
["protostar.contracts"]
main = ["./contracts/settling_game/Arbiter.cairo"]

["protostar.test"]
disable-hint-validation = true
